### ISSUE TITLE
Musanokir Shrine

### ISSUE THREAD

**Issue by FrozenMoon** [Slluxx/TOTK-Interactive-Map#7]
```
{
coords: [19396,8436],
name: "Musanokir Shrine",
text: "",
level: "Ground/Sky/Underground"
}
```

**Comment by HenryKleinschmidt** [comment]
> {
> coords: [19396,8436],
> name: "Musanokir Shrine",
> text: "Swing to Hit",
> level: "Ground"
> }

Added some missing information :)

**Comment by Slluxx** [comment]
Will be added in next update
